In [2]:
import numpy as np

In [21]:
import pandas as pd

In [32]:
data = np.random.randn(4,3)

In [33]:
data

array([[ 0.70196802,  0.75519536, -1.03439343],
       [-0.5184772 ,  0.64202553, -1.52078427],
       [-0.17150453,  0.76633199,  2.40646681],
       [-2.07336185, -0.2314378 ,  0.42520879]])

In [34]:
data_frame = pd.DataFrame(data)

In [35]:
data_frame

0         1         2
0  0.701968  0.755195 -1.034393
1 -0.518477  0.642026 -1.520784
2 -0.171505  0.766332  2.406467
3 -2.073362 -0.231438  0.425209

In [36]:
type(data_frame)

pandas.core.frame.DataFrame

In [37]:
type(data_frame[0])

pandas.core.series.Series

In [38]:
new_df = pd.DataFrame(data, index = ["Atil" , "Zeynep" , "Atlas" , "Mehmet"] , columns = ["Salary" , "Age" , "Seniority"])

In [39]:
new_df

Salary       Age  Seniority
Atil    0.701968  0.755195  -1.034393
Zeynep -0.518477  0.642026  -1.520784
Atlas  -0.171505  0.766332   2.406467
Mehmet -2.073362 -0.231438   0.425209

In [40]:
np.random.randint(10, size=(3, 3))

array([[6, 6, 1],
       [7, 9, 0],
       [5, 2, 5]])

In [41]:
new_df["Age"]

Atil      0.755195
Zeynep    0.642026
Atlas     0.766332
Mehmet   -0.231438
Name: Age, dtype: float64

In [43]:
new_df[ ["Age" , "Salary"] ]

Age    Salary
Atil    0.755195  0.701968
Zeynep  0.642026 -0.518477
Atlas   0.766332 -0.171505
Mehmet -0.231438 -2.073362

In [44]:
new_df.loc["Atil"]

Salary       0.701968
Age          0.755195
Seniority   -1.034393
Name: Atil, dtype: float64

In [45]:
new_df.iloc[0]

Salary       0.701968
Age          0.755195
Seniority   -1.034393
Name: Atil, dtype: float64

In [46]:
new_df.iloc[1]

Salary      -0.518477
Age          0.642026
Seniority   -1.520784
Name: Zeynep, dtype: float64

In [47]:
new_df

Salary       Age  Seniority
Atil    0.701968  0.755195  -1.034393
Zeynep -0.518477  0.642026  -1.520784
Atlas  -0.171505  0.766332   2.406467
Mehmet -2.073362 -0.231438   0.425209

In [48]:
new_df.iloc[:,1]

Atil      0.755195
Zeynep    0.642026
Atlas     0.766332
Mehmet   -0.231438
Name: Age, dtype: float64

In [49]:
new_df["Extra"] = 10

In [50]:
new_df

Salary       Age  Seniority  Extra
Atil    0.701968  0.755195  -1.034393     10
Zeynep -0.518477  0.642026  -1.520784     10
Atlas  -0.171505  0.766332   2.406467     10
Mehmet -2.073362 -0.231438   0.425209     10

In [51]:
new_df.drop("Extra", axis=1)

Salary       Age  Seniority
Atil    0.701968  0.755195  -1.034393
Zeynep -0.518477  0.642026  -1.520784
Atlas  -0.171505  0.766332   2.406467
Mehmet -2.073362 -0.231438   0.425209

In [52]:
new_df

Salary       Age  Seniority  Extra
Atil    0.701968  0.755195  -1.034393     10
Zeynep -0.518477  0.642026  -1.520784     10
Atlas  -0.171505  0.766332   2.406467     10
Mehmet -2.073362 -0.231438   0.425209     10

In [53]:
new_df.drop("Extra", axis=1, inplace=True)

In [54]:
new_df

Salary       Age  Seniority
Atil    0.701968  0.755195  -1.034393
Zeynep -0.518477  0.642026  -1.520784
Atlas  -0.171505  0.766332   2.406467
Mehmet -2.073362 -0.231438   0.425209

In [55]:
new_df.drop("Mehmet", axis=0)

Salary       Age  Seniority
Atil    0.701968  0.755195  -1.034393
Zeynep -0.518477  0.642026  -1.520784
Atlas  -0.171505  0.766332   2.406467

In [56]:
new_df

Salary       Age  Seniority
Atil    0.701968  0.755195  -1.034393
Zeynep -0.518477  0.642026  -1.520784
Atlas  -0.171505  0.766332   2.406467
Mehmet -2.073362 -0.231438   0.425209

In [57]:
new_df.loc["Atlas","Salary"]

-0.17150453338655877

In [58]:
new_df.loc["Atlas","Salary"] = 100

In [59]:
new_df

Salary       Age  Seniority
Atil      0.701968  0.755195  -1.034393
Zeynep   -0.518477  0.642026  -1.520784
Atlas   100.000000  0.766332   2.406467
Mehmet   -2.073362 -0.231438   0.425209

In [60]:
new_df > 0

Salary    Age  Seniority
Atil      True   True      False
Zeynep   False   True      False
Atlas     True   True       True
Mehmet   False  False       True

In [61]:
boolean_frame = new_df > 0

In [62]:
new_df[boolean_frame]

Salary       Age  Seniority
Atil      0.701968  0.755195        NaN
Zeynep         NaN  0.642026        NaN
Atlas   100.000000  0.766332   2.406467
Mehmet         NaN       NaN   0.425209

In [63]:
new_df[new_df > 0]

Salary       Age  Seniority
Atil      0.701968  0.755195        NaN
Zeynep         NaN  0.642026        NaN
Atlas   100.000000  0.766332   2.406467
Mehmet         NaN       NaN   0.425209

In [64]:
new_df[new_df["Salary"] > 1]

Salary       Age  Seniority
Atlas   100.0  0.766332   2.406467

In [65]:
new_df[new_df["Age"] > 0]

Salary       Age  Seniority
Atil      0.701968  0.755195  -1.034393
Zeynep   -0.518477  0.642026  -1.520784
Atlas   100.000000  0.766332   2.406467

In [66]:
new_df

Salary       Age  Seniority
Atil      0.701968  0.755195  -1.034393
Zeynep   -0.518477  0.642026  -1.520784
Atlas   100.000000  0.766332   2.406467
Mehmet   -2.073362 -0.231438   0.425209

In [67]:
new_df.reset_index()

index      Salary       Age  Seniority
0    Atil    0.701968  0.755195  -1.034393
1  Zeynep   -0.518477  0.642026  -1.520784
2   Atlas  100.000000  0.766332   2.406467
3  Mehmet   -2.073362 -0.231438   0.425209

In [68]:
new_df

Salary       Age  Seniority
Atil      0.701968  0.755195  -1.034393
Zeynep   -0.518477  0.642026  -1.520784
Atlas   100.000000  0.766332   2.406467
Mehmet   -2.073362 -0.231438   0.425209

In [70]:
reset_frame = new_df.reset_index()

In [71]:
reset_frame

index      Salary       Age  Seniority
0    Atil    0.701968  0.755195  -1.034393
1  Zeynep   -0.518477  0.642026  -1.520784
2   Atlas  100.000000  0.766332   2.406467
3  Mehmet   -2.073362 -0.231438   0.425209

In [72]:
reset_frame.loc[0]

index            Atil
Salary       0.701968
Age          0.755195
Seniority   -1.034393
Name: 0, dtype: object

In [73]:
new_indices = ["Ati", "Zey", "Atl", "Meh"]

In [74]:
new_df["NewIndex"] = new_indices

In [75]:
new_df

Salary       Age  Seniority NewIndex
Atil      0.701968  0.755195  -1.034393      Ati
Zeynep   -0.518477  0.642026  -1.520784      Zey
Atlas   100.000000  0.766332   2.406467      Atl
Mehmet   -2.073362 -0.231438   0.425209      Meh

In [80]:
# multi index
first_index = ["Simpson","Simpson","Simpson","South Park", "South Park", "South Park"]
inner_index = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]
zipped_index = list(zip(first_index, inner_index))

In [81]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [82]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [83]:
sample_values = np.ones((6,2))
sample_values

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [84]:
big_df = pd.DataFrame(sample_values, index=zipped_index, columns=["Age", "Salary"])
big_df

Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [85]:
big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [86]:
big_df.loc["Simpson"]

Age  Salary
Homer  1.0     1.0
Bart   1.0     1.0
Marge  1.0     1.0

In [87]:
big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64