In [1]:
import numpy as np

In [2]:
#!pip install numpy

In [3]:
my_list = [10,20,30,40]

In [4]:
type(my_list)

list

In [5]:
np.array(my_list)

array([10, 20, 30, 40])

In [6]:
my_numpy_array = np.array(my_list)

In [7]:
type(my_numpy_array)

numpy.ndarray

In [8]:
my_numpy_array.max()

40

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.random.random(5)

array([0.21565913, 0.81268342, 0.40462807, 0.91653257, 0.11098303])

In [12]:
#array arithmetic 

In [13]:
my_list1 = [1,2]

In [14]:
my_list2 = [2,3]

In [15]:
my_list1 + my_list2

[1, 2, 2, 3]

In [16]:
my_numpy_array1 = np.array(my_list1)

In [17]:
my_numpy_array2 = np.array(my_list2)

In [18]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [19]:
myList1 = [1,1]

In [20]:
myList2 = [2,1]

In [21]:
myList3 = [4,5]

In [22]:
my_numpy_array11 = np.array(myList1) 

In [23]:
my_numpy_array12 = np.array(myList2)

In [24]:
my_numpy_array13 = np.array(myList3) 

In [25]:
my_numpy_array11 + my_numpy_array12 + my_numpy_array13

array([7, 7])

In [26]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [27]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [28]:
my_numpy_array1 * 5

array([ 5, 10])

In [29]:
other_array = np.array( [10,20,30,40,50])

In [30]:
other_array.min()

10

In [31]:
other_array.sum()

150

In [32]:
#indexing & arange

In [33]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
 list(range(5,16,3))

[5, 8, 11, 14]

In [35]:
np_array = np.arange(0,10)

In [36]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np_array[0]

0

In [38]:
np_array[-1]

9

In [39]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [40]:
np_array[1:4:]

array([1, 2, 3])

In [41]:
np_array[2:6:2]

array([2, 4])

In [42]:
# random

In [43]:
np.random.randn(4)

array([-0.5687548 , -0.2551566 ,  0.45035013, -0.50749948])

In [44]:
np.random.randn(4,4)

array([[ 1.0680553 , -0.50865219,  0.49304814,  0.66099179],
       [ 0.54549177,  0.35344619, -1.20771895, -1.02609188],
       [-0.82673216, -0.53605948,  2.80085576, -1.40149546],
       [ 0.50249594, -0.82078512, -1.02006597,  0.0432851 ]])

In [45]:
np.random.randint(1,300,5)

array([130, 106, 110, 151,  64])