In [1]:
import numpy as np

In [5]:
my_matrix = [ [5,10] , [15,20] ]

In [7]:
my_matrix[0]

[5, 10]

In [ ]:
my_matrix[]

In [8]:
# row x column

In [10]:
numpy_matrix = np.array( [[5,10] , [15,20]] )

In [11]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [12]:
numpy_matrix[1][0]

15

In [13]:
numpy_matrix.sum()

50

In [14]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
# matrix arithmetic 

In [19]:
first_array = np.array([[10,20] , [30,40]])

In [20]:
second_array = np.array( [[5,15] , [25,35]])

In [21]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [24]:
third_array = np.array([[50,60]])

In [25]:
third_array

array([[50, 60]])

In [26]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [27]:
fourth_array = np.array([[10,20,30,40,50]])

In [30]:
fourth_array.shape

(1, 5)

In [31]:
first_array.shape

(2, 2)

In [32]:
# matrix multiplication

In [33]:
# dot product

In [34]:
first_matrix = np.array([[10,20,30]])

In [35]:
first_matrix

array([[10, 20, 30]])

In [36]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [37]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [38]:
first_matrix.shape

(1, 3)

In [39]:
second_matrix.shape

(3, 2)

In [40]:
result_matrix = first_matrix.dot(second_matrix)

In [41]:
result_matrix

array([[120, 180]])

In [42]:
result_matrix.shape

(1, 2)