In [41]:
import numpy as np

In [42]:
new_array = np.random.randint(1,100,20)

In [43]:
new_array

array([51, 70, 49, 56, 27, 47, 82, 93, 68, 78,  9, 16, 28, 75, 95,  9, 33,
        1, 99, 73])

In [44]:
new_array > 25

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True, False,  True, False,
        True,  True])

In [45]:
new_array[new_array > 25]

array([51, 70, 49, 56, 27, 47, 82, 93, 68, 78, 28, 75, 95, 33, 99, 73])

In [46]:
new_array[new_array < 25]

array([ 9, 16,  9,  1])

In [47]:
#transpose & reshape

In [48]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [49]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [50]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [51]:
random_array = np.random.random((6,1))

In [52]:
random_array

array([[0.96686812],
       [0.44230003],
       [0.40708983],
       [0.70770287],
       [0.7262883 ],
       [0.81039538]])

In [53]:
random_array.shape

(6, 1)

In [54]:
random_array.reshape(2,3)

array([[0.96686812, 0.44230003, 0.40708983],
       [0.70770287, 0.7262883 , 0.81039538]])

In [55]:
random_array.reshape(3,2)

array([[0.96686812, 0.44230003],
       [0.40708983, 0.70770287],
       [0.7262883 , 0.81039538]])

In [56]:
# z-score

In [57]:
data = np.array([10, 12, 13, 15, 18, 25, 100, 105])

In [58]:
# outlier

In [59]:
mean = np.mean(data)

In [60]:
mean

37.25

In [61]:
data.sum() / len(data)

37.25

In [62]:
std = np.std(data)

In [63]:
std

37.9333296719389

In [64]:
z_scores = (data - mean) / std

In [65]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [66]:
np.abs(z_scores) > 1

array([False, False, False, False, False, False,  True,  True])

In [67]:
data[z_scores > 1]

array([100, 105])

In [68]:
# math equations

In [69]:
# Solve 2x + 3y = 8 and 5x + 7y = 19

In [70]:
# Coefficients matrix
A = np.array([[2, 3], [5, 7]])

In [71]:
# Constants matrix
b = np.array([8, 19])

In [72]:
# Solve for x and y
solution = np.linalg.solve(A, b)

In [73]:
solution

array([1., 2.])

In [74]:
# data analysis